### PR TITLE
binning and profiling format rename

### PR DESCRIPTION
**Pull request by pbelmann**
#55

### CODE REVIEW

**Comment by michaelbarton** [comment]
I feel like we should aim for these two formats to be widely adopted by the bioinformatics community rather than specific to the CAMI challenge. Naming it the CAMI binning format suggests to me that there are other formats. You include the text in the spec that this was generated as part of the CAMI challenge and ask that people cite it once the paper is published?

**Comment by pbelmann** [comment]
> I feel like we should aim for these two formats to be widely adopted by the bioinformatics community rather than specific to the CAMI challenge. Naming it the CAMI binning format suggests to me that there are other formats. 

I agree, maybe we should not do that. I will create a new PR.

> You include the text in the spec that this was generated as part of the CAMI challenge and ask that people cite it once the paper is published?

Yes. I think when a bioboxes paper appear, it should cite CAMI regarding this formats.

**Comment by pbelmann** [comment]
I created a new PR #57,  without renaming the formats, just with CAMI mentioned in the spec.

**Comment by michaelbarton** [comment]
Closed in favor of #68

**Pull request closed without merging**
